name: earth-analytics-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  # Core scientific python
  - numpy
  - matplotlib
  - pyqt
  - seaborn
  - tqdm
  - kiwisolver

  # Spatial packages
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - contextily
  - pysal
  - pyproj
  - folium
  - geojson
  - earthpy

  # Natural language processing
  - nltk
  - textblob

  # Jupyter Environment
  - autopep8
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - jupyterlab
  - nb_conda
  - nbclean
  - mapboxgl
  - hydrofunctions
  - scikit-learn
  - geocoder
  - tweepy
